version: "3.2"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    restart: unless-stopped
  db:
    image: postgres:14
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - ./.docker/volumes/db/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped
  supertokens:
    image: "registry.supertokens.io/supertokens/supertokens-postgresql:5.0"
    depends_on:
      - db
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      API_KEYS: "${API_KEY}"
      PASSWORD_RESET_TOKEN_LIFETIME: 1209600000
    ports:
      - 127.0.0.1:3567:3567
    restart: unless-stopped
  app-db:
    image: postgres:14
    environment:
      - "POSTGRES_USER=${POSTGRES_APP_USER}"
      - "POSTGRES_DB=${POSTGRES_APP_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_APP_PASSWORD}"
    volumes:
      - ./.docker/volumes/app-db/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped

